version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: budgetapp
      MYSQL_USER: newuser
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
